// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: searchengine/v1/search_engine.proto

package searchenginev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_searchengine_v1_search_engine_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_searchengine_v1_search_engine_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SearchResult) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SearchResult) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_searchengine_v1_search_engine_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	PageNumber    int32                  `protobuf:"varint,4,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_searchengine_v1_search_engine_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Chunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Chunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Chunk) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *Chunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type IndexChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexChunksRequest) Reset() {
	*x = IndexChunksRequest{}
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexChunksRequest) ProtoMessage() {}

func (x *IndexChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexChunksRequest.ProtoReflect.Descriptor instead.
func (*IndexChunksRequest) Descriptor() ([]byte, []int) {
	return file_searchengine_v1_search_engine_proto_rawDescGZIP(), []int{4}
}

func (x *IndexChunksRequest) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type IndexChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexedCount  int32                  `protobuf:"varint,1,opt,name=indexed_count,json=indexedCount,proto3" json:"indexed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexChunksResponse) Reset() {
	*x = IndexChunksResponse{}
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexChunksResponse) ProtoMessage() {}

func (x *IndexChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchengine_v1_search_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexChunksResponse.ProtoReflect.Descriptor instead.
func (*IndexChunksResponse) Descriptor() ([]byte, []int) {
	return file_searchengine_v1_search_engine_proto_rawDescGZIP(), []int{5}
}

func (x *IndexChunksResponse) GetIndexedCount() int32 {
	if x != nil {
		return x.IndexedCount
	}
	return 0
}

var File_searchengine_v1_search_engine_proto protoreflect.FileDescriptor

const file_searchengine_v1_search_engine_proto_rawDesc = "" +
	"\n" +
	"#searchengine/v1/search_engine.proto\x12\x0fsearchengine.v1\x1a\x1cgoogle/api/annotations.proto\"N\n" +
	"\rSearchRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x84\x01\n" +
	"\fSearchResult\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"\x90\x01\n" +
	"\x0eSearchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.searchengine.v1.SearchResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x95\x01\n" +
	"\x05Chunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1f\n" +
	"\vpage_number\x18\x04 \x01(\x05R\n" +
	"pageNumber\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\"D\n" +
	"\x12IndexChunksRequest\x12.\n" +
	"\x06chunks\x18\x01 \x03(\v2\x16.searchengine.v1.ChunkR\x06chunks\":\n" +
	"\x13IndexChunksResponse\x12#\n" +
	"\rindexed_count\x18\x01 \x01(\x05R\findexedCount2\xcc\x01\n" +
	"\rSearchService\x12a\n" +
	"\x06Search\x12\x1e.searchengine.v1.SearchRequest\x1a\x1f.searchengine.v1.SearchResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/search\x12X\n" +
	"\vIndexChunks\x12#.searchengine.v1.IndexChunksRequest\x1a$.searchengine.v1.IndexChunksResponseBWZUgithub.com/knowledge-search-system/search-engine/proto/searchengine/v1;searchenginev1b\x06proto3"

var (
	file_searchengine_v1_search_engine_proto_rawDescOnce sync.Once
	file_searchengine_v1_search_engine_proto_rawDescData []byte
)

func file_searchengine_v1_search_engine_proto_rawDescGZIP() []byte {
	file_searchengine_v1_search_engine_proto_rawDescOnce.Do(func() {
		file_searchengine_v1_search_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_searchengine_v1_search_engine_proto_rawDesc), len(file_searchengine_v1_search_engine_proto_rawDesc)))
	})
	return file_searchengine_v1_search_engine_proto_rawDescData
}

var file_searchengine_v1_search_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_searchengine_v1_search_engine_proto_goTypes = []any{
	(*SearchRequest)(nil),       // 0: searchengine.v1.SearchRequest
	(*SearchResult)(nil),        // 1: searchengine.v1.SearchResult
	(*SearchResponse)(nil),      // 2: searchengine.v1.SearchResponse
	(*Chunk)(nil),               // 3: searchengine.v1.Chunk
	(*IndexChunksRequest)(nil),  // 4: searchengine.v1.IndexChunksRequest
	(*IndexChunksResponse)(nil), // 5: searchengine.v1.IndexChunksResponse
}
var file_searchengine_v1_search_engine_proto_depIdxs = []int32{
	1, // 0: searchengine.v1.SearchResponse.results:type_name -> searchengine.v1.SearchResult
	3, // 1: searchengine.v1.IndexChunksRequest.chunks:type_name -> searchengine.v1.Chunk
	0, // 2: searchengine.v1.SearchService.Search:input_type -> searchengine.v1.SearchRequest
	4, // 3: searchengine.v1.SearchService.IndexChunks:input_type -> searchengine.v1.IndexChunksRequest
	2, // 4: searchengine.v1.SearchService.Search:output_type -> searchengine.v1.SearchResponse
	5, // 5: searchengine.v1.SearchService.IndexChunks:output_type -> searchengine.v1.IndexChunksResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_searchengine_v1_search_engine_proto_init() }
func file_searchengine_v1_search_engine_proto_init() {
	if File_searchengine_v1_search_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_searchengine_v1_search_engine_proto_rawDesc), len(file_searchengine_v1_search_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_searchengine_v1_search_engine_proto_goTypes,
		DependencyIndexes: file_searchengine_v1_search_engine_proto_depIdxs,
		MessageInfos:      file_searchengine_v1_search_engine_proto_msgTypes,
	}.Build()
	File_searchengine_v1_search_engine_proto = out.File
	file_searchengine_v1_search_engine_proto_goTypes = nil
	file_searchengine_v1_search_engine_proto_depIdxs = nil
}
